name: Build and deploy Node.js app to Azure Web App - Powershell-XML-tool

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20.x'
      APP_DIR: 'NEW_DESIGN_PS'   # <-- your app folder (contains package.json)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      - name: Install deps
        working-directory: ${{ env.APP_DIR }}
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-fund --no-audit
          fi

      - name: Build
        working-directory: ${{ env.APP_DIR }}
        run: npm run build

      # Zip the **app folder itself** so package.json sits at the root of the zip
      - name: Archive site
        working-directory: ${{ env.APP_DIR }}
        run: zip -r site.zip . -x "node_modules/*" ".git/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: Powershell-XML-tool
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CDC3D3CDB19D4EEC84C93BB20902C636 }}
          package: ${{ env.APP_DIR }}/site.zip
