name: Build and deploy Node.js app to Azure Web App - Powershell-XML-tool

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20.x'
      APP_DIR: '.'  # <-- set to subfolder if needed, e.g. 'apps/powershell-parser'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      - name: Install
        working-directory: ${{ env.APP_DIR }}
        run: npm ci

      - name: Build
        working-directory: ${{ env.APP_DIR }}
        run: npm run build

      # Create a clean zip WITHOUT node_modules/.git
      - name: Archive site
        working-directory: ${{ env.APP_DIR }}
        run: |
          zip -r site.zip . -x "node_modules/*" ".git/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: Powershell-XML-tool
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CDC3D3CDB19D4EEC84C93BB20902C636 }}
          package: ${{ env.APP_DIR }}/site.zip
